name: Deploy to PyPi

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        # channel: ["Stable", "Beta", "Dev", "Canary"]
        # only run stable and beta channel until pypi storage problem is fixed
        channel: ["Stable", "Beta"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        run: uv sync

      - name: Download chromedriver and build wheels
        run: uv run build-wheels.py ${{ matrix.channel }}

      - name: Publish distribution to PyPI
        if: ${{ hashFiles('dist/*') != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
